### ISSUE TITLE
Feature request: Cygwin support

### ISSUE THREAD

**Issue by rr-** [AoiKuiyuyou/AoikHotkey#1]
`ValueError: Unsupported platform: 'cygwin'.`

:-(

While pywin32 doesn't support cygwin, it can still be done with `ctypes` like this:

    user32 = ctypes.cdll.LoadLibrary('user32.dll')

    LONG = ctypes.c_int32
    BOOL = ctypes.c_int
    HANDLE = ctypes.c_void_p
    if ctypes.sizeof(ctypes.c_long) == ctypes.sizeof(ctypes.c_void_p):
        WPARAM = ctypes.c_ulong
        LPARAM = ctypes.c_long
    elif ctypes.sizeof(ctypes.c_longlong) == ctypes.sizeof(ctypes.c_void_p):
        WPARAM = ctypes.c_ulonglong
        LPARAM = ctypes.c_longlong

etc.

**Comment by AoiKuiyuyou** [comment]
The [pull request](https://github.com/AoiKuiyuyou/AoikHotkey/pull/2) has been merged.
