### ISSUE TITLE
click f2  ,closepage not run,why

### ISSUE THREAD

**Issue by wagic520** [AoiKuiyuyou/AoikHotkey#4]
#3 
import win32gui
import win32api
import win32clipboard 
import keyboard
import threading
import win32con
import struct
import mouse
import time

   
def closepage():
    print("closepage")

def f2func():
    drawline()
def waitfindcolor(x,y,r,l,c):
    cx=0
    i=0
    while  cx==0:
        time.sleep(0.2)
        i+=1
        if i>20 :
            return False
    return True

def drawline():
    if waitfindcolor(42,178,43,179,(236,233,216)):
        i=1
        return

def mainhotkey():
    delete=keyboard.add_hotkey("delete",closepage,None,False)
    f2key=keyboard.add_hotkey("f2",f2func,None,True)

if __name__ == '__main__':
    mainhotkey()
    keyboard.wait('alt+esc')

**Comment by AoiKuiyuyou** [comment]
Both `delete` and `f2` bind correctly. Check your called function.
