### ISSUE TITLE
Cannot bind to anything with spacebar (Linux)

### ISSUE THREAD

**Issue by TheLastProject** [AoiKuiyuyou/AoikHotkey#5]
I seem to be unable to bind to spacebar at all.

Using something like
```
('^+p', launch_pext),
```
in the SPEC part of the config file works great!

But if I try to use space in any way instead of p (I've tried simply `^+ `, but also `^+{ }`, `^+0` and `^+{0}`), it doesn't seem to actually respond to space.

When I press Ctrl Shift Space, efunc_no_mouse states this:

```
# LCTRL LSHIFT 0(+)
VK=0 (0x0) Name='' Event=key down

^@# LCTRL LSHIFT 0(-)
VK=0 (0x0) Name='' Event=key up
```

Am I missing something? Looking through the code it does seem spacebar is supposed to be supported, but I cannot get it to work.

**Comment by AoiKuiyuyou** [comment]
In Linux, the key name reported by event manager is mapped to a virtual key using dict [MAP_X11_NAME_TO_WIN_VK](https://github.com/AoiKuiyuyou/AoikHotkey/blob/0.6.0/src/aoikhotkey/virtualkey.py#L330) at [here](https://github.com/AoiKuiyuyou/AoikHotkey/blob/0.6.0/src/aoikhotkey/hotkey_manager.py#L641). The key name for space is `space` which is not included in the mapping dict so a default virtual key 0 is used.

As a quick fix, add an entry `'space': VK_SPACE,` to [MAP_X11_NAME_TO_WIN_VK](https://github.com/AoiKuiyuyou/AoikHotkey/blob/0.6.0/src/aoikhotkey/virtualkey.py#L330).

In case any other key is not working in Linux, the way to find the key name is to add a `print(event.Key)`  before [this line](https://github.com/AoiKuiyuyou/AoikHotkey/blob/0.6.0/src/aoikhotkey/hotkey_manager.py#L641).

I will fix this in the next version.
